### ISSUE TITLE
Queues statisitcs doesn't appear despite the correct configuration

### ISSUE THREAD

**Issue by mika123321** [AnnaCzyrko/motech-crowd#6]
Enviroment:
Browser: Mozilla Firefox Quantum 65.0.1
System: Ubuntu 14-04 LTS (Oracle VM VirtualBox 6.1.18)
Version: 0.28

Pre-conditions: User is log in to application as an Admin. User is on the main page "Home". MOTECH is correctly configured.

Steps:
1. Scroll down the main page.
2. Click "Queues" in "View Diagnostics" area.

Expected result: Queues are visible.
Current result: There is an error "Could not retrieve queue statistics due to an error. Please check the documentation."
![Queue](https://user-images.githubusercontent.com/44918875/114282707-bed54180-9a45-11eb-8542-9ef69835e386.PNG)

**Comment by Patrycja-Weihs** [comment]
Statystki kolejki i topików pojawiają się, trzeba tylko skonfigurować activemq tak jak jest napisane w instrukcji. Trochę się z tym namęczyłam, ale są. Próbowałaś?
Why am I not seeing anything in “Admin Queues and Topics”?
Edit ActiveMQ broker configuration, which is in the file /etc/activemq/instances-enabled/main/activemq.xml. Change or add the following attribute to the broker element:

<broker useJmx="true">
The next step is to restart ActiveMQ. To restart ActiveMQ use

sudo service activemq restart
If the issue still appears, restart MOTECH (Tomcat).

**Comment by mika123321** [comment]
Hmmm... Tylko, że ja tak zrobiłam i dalej nic.

**Comment by mika123321** [comment]
Could be caused by wrong configuration.
